### ISSUE TITLE
Exception on startup  'bad argument to format'

### ISSUE THREAD

**Issue by FichteFoll** [darsain/uosc#6]
Used to work until yesterday, but since then I get this traceback on startup:
```
      uosc:
      uosc: stack traceback:
      uosc: 	[C]: in function 'format'
      uosc: 	mp.assdraw:28: in function 'coord'
      uosc: 	mp.assdraw:54: in function 'line_to'
      uosc: 	mp.assdraw:74: in function 'rect_cw'
      uosc: 	/home/fichte/.config/mpv/scripts/uosc.lua:1264: in function </home/fichte/.config/mpv/scripts/uosc.lua:1177>
      uosc: 	(...tail calls...)
      uosc: 	/home/fichte/.config/mpv/scripts/uosc.lua:1751: in function 'cb'
      uosc: 	mp.defaults:346: in function 'process_timers'
      uosc: 	mp.defaults:506: in function 'dispatch_events'
      uosc: 	mp.defaults:479: in function <mp.defaults:478>
      uosc: 	[C]: in ?
      uosc: 	[C]: in ?
      uosc: Lua error: mp.assdraw:28: bad argument #3 to 'format' (not a number in proper range)
```

mpv 0.32, Arch Linux, no uosc.conf
